name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Originally we had this set to every day, as we wanted to test
  # cabal/liquidhaskell builds frequently for upstream breaks. However, there
  # really isn't a need to run these other jobs every day. So how often should
  # we?
  #
  # Arguably we only need to run them on a change, as they __should't__
  # rely on upstream changes, other than the jobs themselves. But it's
  # possible something goes wrong with nix e.g. the cache, so it seems fine
  # to leave them running weekly for now.
  schedule:
    # Every Sunday at 00:00 UTC.
    #
    # https://crontab.guru
    - cron: '0 0 * * 0'

  workflow_dispatch:

# see NOTE: [Manageable CI]

jobs:
  # Need to run these separately as there is not enough space to run them
  # all on the same machine.
  default:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "ghc8107"
          - "ghc902"
          - "ghc925"
          - "ghc926"
          - "ghc927"
          - "ghc928"
          - "ghc945"
          - "ghc946"
          - "ghc947"
          - "ghc948"
          - "ghc962"
          - "ghc963"
          - "ghc964"
          - "ghc965"
          - "ghc981"
          - "ghc982"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      # There is a tension here in that we would like to test loading each shell
      # will all shells, but that can require more storage than our free runner
      # allows. For now, we are able to load all tools except hls, so that is
      # what we do. But we may need to further pare it down in the future.
      - name: Load shell
        run: |
          ./test/load_shell.sh \
            --ghc ${{ matrix.ghc }} \
            --hls false \
            --verbose

  # It turns out we _do_ have enough storage to load hls by itself.
  hls:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "ghc8107"
          - "ghc902"
          - "ghc925"
          - "ghc926"
          - "ghc927"
          - "ghc928"
          - "ghc945"
          - "ghc946"
          - "ghc947"
          - "ghc948"
          - "ghc962"
          - "ghc963"
          - "ghc964"
          #- "ghc965"
          - "ghc981"
          - "ghc982"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Load shell with hls
        run: |
          ./test/load_shell.sh \
            --ghc ${{ matrix.ghc }} \
            --no-tools \
            --hls true \
            --verbose

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Format
        run: |
          nix run ./ci#format
          git diff --exit-code --color=always
