name: ghc

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ghc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: ghcid = true
        run: nix-shell . -A ghc --arg ghcid true --dry-run

      - name: hls = true
        run: nix-shell . -A ghc --arg hls true --dry-run

      - name: ghcVers = ghc927
        run: nix-shell . -A ghc --argstr ghcVers ghc927 --dry-run

      - name: Clone ghc
        uses: actions/checkout@v3.5.0
        with:
          repository: ghc/ghc
          ref: master
          path: ./ghc-build
          submodules: recursive

      - name: Build
        run: |
          nix-shell . -A ghc --run '
            cd ./ghc-build \
              && cabal update \
              && ghc_fbuild'
