name: libs

# Tests building external libs we care about. We want this to run frequently
# so that upstream changes are handled.

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # Every day at 00:00 UTC.
    #
    # https://crontab.guru
    - cron: '0 0 * * 0-6'

  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Clone cabal
        uses: actions/checkout@v3
        with:
          repository: haskell/cabal
          ref: master
          path: ./cabal-build

      - name: Build
        run: |
          nix-shell . -A default --argstr ghcVers ghc963 --run '
            cd ./cabal-build \
              && cabal update \
              && cabal build cabal-install'

  liquidhaskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Clone liquidhaskell
        uses: actions/checkout@v3
        with:
          repository: ucsd-progsys/liquidhaskell
          ref: develop
          path: ./liquidhaskell-build
          submodules: recursive

      - name: hls = true
        run: nix-shell . -A liquidhaskell --arg hls true --dry-run

      - name: Build
        run: |
          nix-shell . -A liquidhaskell --run '
            cd ./liquidhaskell-build \
              && cabal update \
              && cabal build'

      - name: Test
        run: |
          nix-shell . -A liquidhaskell --run '
            cd ./liquidhaskell-build \
              && cabal update \
              && ./scripts/test/test_plugin.sh'
