name: libs

# Tests building external libs we care about. We want this to run frequently
# so that upstream changes are handled.

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # Every day at 00:00 UTC.
    #
    # https://crontab.guru
    - cron: '0 0 * * 0-6'

  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Clone cabal
        uses: actions/checkout@v4
        with:
          repository: haskell/cabal
          ref: master
          path: ./cabal-build

      - name: Build
        run: |
          nix-shell . -A default --argstr ghcVers ghc963 --run '
            cd ./cabal-build \
              && cabal update \
              && cabal build cabal-install'

  liquidhaskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Clone liquidhaskell
        uses: actions/checkout@v4
        with:
          repository: ucsd-progsys/liquidhaskell
          ref: develop
          path: ./liquidhaskell-build
          submodules: recursive

      - name: hls = true
        run: nix-shell . -A liquidhaskell --arg hls true --dry-run

      - name: Build
        run: |
          nix-shell . -A liquidhaskell --run '
            cd ./liquidhaskell-build \
              && cabal update \
              && cabal build'

      - name: Test
        run: |
          nix-shell . -A liquidhaskell --run '
            cd ./liquidhaskell-build \
              && cabal update \
              && ./scripts/test/test_plugin.sh'
