name: liquidhaskell

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  liquidhaskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Clone liquidhaskell
        uses: actions/checkout@v3.5.0
        with:
          repository: ucsd-progsys/liquidhaskell
          ref: develop
          path: ./liquidhaskell-build
          submodules: recursive

      - name: cabalPlan = true
        run: nix-shell . -A liquidhaskell --arg cabalPlan true --dry-run

      - name: ghcid = true
        run: nix-shell . -A liquidhaskell --arg ghcid true --dry-run

      - name: hls = true
        run: nix-shell . -A liquidhaskell --arg hls true --dry-run

      - name: Build
        run: |
          nix-shell . -A liquidhaskell --run '
            cd ./liquidhaskell-build \
              && cabal update \
              && cabal build'

      - name: Test
        run: |
          nix-shell . -A liquidhaskell --run '
            cd ./liquidhaskell-build \
              && cabal update \
              && cabal test'