name: safe-exceptions

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  safe-exceptions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
        - "ghc8107"
        - "ghc902"
        - "ghc925"
        - "ghc944"
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Clone safe-exceptions
        uses: actions/checkout@v3.0.2
        with:
          repository: fpco/safe-exceptions
          ref: master
          path: ./safe-exceptions-build

      - name: Build
        run: |
          nix-shell . -A default --argstr ghcVers ${{ matrix.ghc }} --arg ghcid false --argstr hls none --run '
            cd ./safe-exceptions-build \
              && cabal update \
              && cabal build'
